### ISSUE TITLE
replicate original shape bias results using ImageNet trained ResNet-50

### ISSUE THREAD

**Issue by wkvong** [alexatartaglini/developmental-shape-bias#2]
this is probably a good starting point to make sure everything else we're doing is sensible, and this is the only model the original paper reports as using the torchvision model (rather than some other deep learning library), and we can check the classification decisions to see if the model outputs anything other than the shape or texture categories for each stimuli.

their results on ResNet-50: 22.1% (shape) vs. 77.9% (texture)

also small detail I caught in their appendix: "For our analysis of texture vs. shape biases (Figure 4), we excluded trials for which no cue conflict was present (i.e., those trials where a bicycle content image was fused with a bicycle texture image, hence no texture-shape cue conflict present)." so it sounds like filenames like "airplane10-airplane1.png" should be excluded.

**Comment by wkvong** [comment]
adding more details I found at the bottom of the original repo: https://github.com/rgeirhos/texture-vs-shape, the degree of shape or texture bias is only calculated by the subset of images that are either correctly classified as the shape category or the texture category. furthermore it does seem like the overall accuracy (as either shape or texture) does seem to be pretty low based on what I read here (from Emin surprisingly enough!): https://github.com/rgeirhos/texture-vs-shape/issues/6

**Comment by alexatartaglini** [comment]
This is fixed now. Currently, we have the following results on the Geirhos style transfer dataset (disregarding "neither decisions," which make up 33% of ResNet-50 decisions and 58% of SAYCAM decisions):

**ResNet-50:**
Shape: 22.15%
Texture: 77.84%

**SAYCAM:**
Shape: 42.2%
Texture: 57.8%
